### ISSUE TITLE
Hashing the key

### ISSUE THREAD

**Issue by VijitCoder** [ioncube/php-openssl-cryptor#8]
Why the key hashed with `php::openssl_digest()`? As far as I understand, real strong encryption relies on the initial vector, the key's hash doesn't matter here.. I read the manual about  `php::openssl_encrypt()`, explored examples and comments there, read `openssl enc` wiki. I saw [the comment](http://php.net/manual/en/function.openssl-encrypt.php#104438) about password/key subtitution, but I think, yours intention was in something else. So, what the point?

**Comment by nickion** [comment]
The IV is used so that encrypting the same data with the same key does not produce the same result, and as the IV is necessary for decryption, it is public and embedded as part of the encrypted result. The encryption key is required to be a certain length for the encryption algorithm to work, which is ensured by using a suitable hash function.
